"""
NiftyPulsePro Daily Signal Report
---------------------------------

Reads the latest signals/scan_*.csv generated by the scanner.

IMPORTANT:
The scanner CSV uses the column "Signal" (not "SignalType").
This script derives SignalType from Signal so it works with the
current NiftyPulsePro scanner output.

Creates:
    signals/daily_signal_report.csv
    signals/daily_top20_buy.csv
    signals/daily_top20_sell.csv
    signals/daily_top20_buy_watchlist.csv
    signals/daily_top20_sell_watchlist.csv
"""

from pathlib import Path
import pandas as pd


SIGNAL_DIR = Path("signals")
TOP_N = 20
WATCHLIST_MIN_SCORE = 12


def number(value):
    try:
        if value is None or pd.isna(value):
            return float("nan")
        return float(value)
    except (TypeError, ValueError):
        return float("nan")


def is_true(value):
    if isinstance(value, bool):
        return value
    if value is None or pd.isna(value):
        return False

    text = str(value).strip().lower()
    return text in {"true", "1", "yes", "y", "up", "down"}


def latest_scan_file():
    files = sorted(SIGNAL_DIR.glob("scan_*.csv"))
    if not files:
        raise FileNotFoundError(
            "No scan_*.csv files found in signals/. Run the scanner first."
        )
    return files[-1]


def derive_signal_type(value):
    """
    Convert the scanner's Signal column into BUY / SELL / NONE.

    Handles values such as:
        BUY
        SELL
        NONE
        BUY ...
        SELL / TREND-BREAK
    """
    if value is None or pd.isna(value):
        return "NONE"

    text = str(value).strip().upper()

    if "BUY" in text:
        return "BUY"

    if "SELL" in text:
        return "SELL"

    return "NONE"


def calculate_watch_score(row, direction):
    score = 0

    rsi = number(row.get("RSI"))
    adx = number(row.get("ADX"))
    price = number(row.get("Price"))
    vstop = number(row.get("VStop"))
    trend = str(row.get("Trend", "")).strip().upper()

    if direction == "BUY":
        if trend == "UP":
            score += 3

        if pd.notna(price) and pd.notna(vstop) and price > vstop:
            score += 3

        if is_true(row.get("VolAboveAvg")):
            score += 2

        if is_true(row.get("OBV_OK")):
            score += 2

        if is_true(row.get("RelStrengthOK")):
            score += 2

        if is_true(row.get("MarketRegimeOK")):
            score += 1

        if is_true(row.get("MonthlyConfluence")):
            score += 2

        if is_true(row.get("TrendStrengthOK")):
            score += 2

        if pd.notna(rsi):
            if 50 <= rsi <= 65:
                score += 3
            elif 45 <= rsi < 50:
                score += 2
            elif 40 <= rsi < 45:
                score += 1

    else:
        if trend == "DOWN":
            score += 3

        if pd.notna(price) and pd.notna(vstop) and price < vstop:
            score += 3

        if is_true(row.get("VolAboveAvg")):
            score += 2

        if not is_true(row.get("OBV_OK")):
            score += 2

        if not is_true(row.get("RelStrengthOK")):
            score += 2

        if not is_true(row.get("MarketRegimeOK")):
            score += 1

        if is_true(row.get("TrendStrengthOK")):
            score += 1

        if pd.notna(rsi):
            if 35 <= rsi <= 50:
                score += 3
            elif 50 < rsi <= 55:
                score += 2
            elif 55 < rsi <= 60:
                score += 1

    if pd.notna(adx):
        if adx >= 25:
            score += 2
        elif adx >= 20:
            score += 1

    return score


def prepare_dataframe(df):
    required = ["Symbol", "Timeframe", "Price", "RSI"]

    missing = [col for col in required if col not in df.columns]
    if missing:
        raise ValueError(
            "Scanner output is missing required columns: "
            + ", ".join(missing)
        )

    # CURRENT SCANNER FORMAT:
    # It has "Signal", not "SignalType".
    if "Signal" not in df.columns:
        raise ValueError(
            "Scanner output does not contain the expected 'Signal' column.\n"
            "Available columns are:\n"
            + "\n".join(str(c) for c in df.columns)
        )

    # Derive the report's SignalType from the scanner's Signal column.
    df["SignalType"] = df["Signal"].apply(derive_signal_type)

    for col in ["Price", "Volume", "RSI", "ADX", "VStop", "Score"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    timeframe_rank = {
        "WEEKLY": 2,
        "Weekly": 2,
        "MONTHLY": 1,
        "Monthly": 1,
    }

    df["TimeframeRank"] = (
        df["Timeframe"]
        .astype(str)
        .map(timeframe_rank)
        .fillna(0)
        .astype(int)
    )

    if "Score" not in df.columns:
        df["Score"] = 0.0

    df["Score"] = pd.to_numeric(
        df["Score"], errors="coerce"
    ).fillna(0.0)

    return df


def output_columns(frame):
    preferred = [
        "SignalType",
        "Signal",
        "Symbol",
        "Name",
        "Category",
        "Timeframe",
        "Date",
        "Price",
        "CurrentPrice",
        "PriceDriftPct",
        "StalePrice",
        "PctFrom52WHigh",
        "PullbackZone",
        "Volume",
        "VolAboveAvg",
        "RSI",
        "ADX",
        "TrendStrengthOK",
        "OBV_OK",
        "RelStrengthOK",
        "MarketRegimeOK",
        "MonthlyConfluence",
        "EarningsDaysAway",
        "EarningsSoon",
        "Trend",
        "VStop",
        "Score",
        "BuyWatchScore",
        "SellWatchScore",
        "TimeframeRank",
    ]

    return [c for c in preferred if c in frame.columns]


def select_output(frame, extra=None):
    cols = output_columns(frame)

    for col in extra or []:
        if col in frame.columns and col not in cols:
            cols.append(col)

    return frame[cols].copy()


def main():
    print("=" * 80)
    print("NiftyPulsePro Daily Signal Report")
    print("=" * 80)

    input_file = latest_scan_file()
    print(f"Input: {input_file}")

    df = pd.read_csv(input_file)

    print(f"Scanner rows: {len(df)}")

    if df.empty:
        print("Scanner file is empty.")
        return

    print("Scanner columns:")
    print(", ".join(str(c) for c in df.columns))

    signals = prepare_dataframe(df)
    if "ADX" not in signals.columns:
        signals["ADX"] = float("nan")

    # Calculate Score for confirmed BUY/SELL signals.
    signals["Score"] = signals.apply(lambda row: calculate_watch_score(row, row["SignalType"]) if row["SignalType"] in ("BUY", "SELL") else 0, axis=1)

    # ------------------------------------------------------------
    # WATCHLIST
    # ------------------------------------------------------------

    watch = signals[signals["SignalType"] == "NONE"].copy()

    if not watch.empty:
        watch["BuyWatchScore"] = watch.apply(
            lambda row: calculate_watch_score(row, "BUY"),
            axis=1,
        )

        watch["SellWatchScore"] = watch.apply(
            lambda row: calculate_watch_score(row, "SELL"),
            axis=1,
        )
    else:
        watch["BuyWatchScore"] = pd.Series(
            index=watch.index, dtype=float
        )
        watch["SellWatchScore"] = pd.Series(
            index=watch.index, dtype=float
        )

    # ------------------------------------------------------------
    # CONFIRMED BUY
    # ------------------------------------------------------------

    buys = signals[signals["SignalType"] == "BUY"].copy()

    if not buys.empty:
        buys = buys.sort_values(
            ["Score", "TimeframeRank", "ADX"],
            ascending=[False, False, False],
            na_position="last",
        )

    top20_buy = buys.head(TOP_N).copy()

    # ------------------------------------------------------------
    # CONFIRMED SELL
    # ------------------------------------------------------------

    sells = signals[signals["SignalType"] == "SELL"].copy()

    if not sells.empty:
        sells = sells.sort_values(
            ["Score", "TimeframeRank", "ADX"],
            ascending=[False, False, False],
            na_position="last",
        )

    top20_sell = sells.head(TOP_N).copy()

    # ------------------------------------------------------------
    # BUY WATCHLIST
    # ------------------------------------------------------------

    buy_watch = watch[
        watch["BuyWatchScore"] >= WATCHLIST_MIN_SCORE
    ].copy()

    if not buy_watch.empty:
        buy_watch = buy_watch.sort_values(
            ["BuyWatchScore", "TimeframeRank", "ADX"],
            ascending=[False, False, False],
            na_position="last",
        )

    top20_buy_watch = buy_watch.head(TOP_N).copy()

    # ------------------------------------------------------------
    # SELL WATCHLIST
    # ------------------------------------------------------------

    sell_watch = watch[
        watch["SellWatchScore"] >= WATCHLIST_MIN_SCORE
    ].copy()

    if not sell_watch.empty:
        sell_watch = sell_watch.sort_values(
            ["SellWatchScore", "TimeframeRank", "ADX"],
            ascending=[False, False, False],
            na_position="last",
        )

    top20_sell_watch = sell_watch.head(TOP_N).copy()

    # ------------------------------------------------------------
    # ADD WATCHLIST SCORES TO FULL REPORT
    # ------------------------------------------------------------

    full_report = signals.copy()

    if not watch.empty:
        score_columns = watch[
            ["Symbol", "Timeframe", "BuyWatchScore", "SellWatchScore"]
        ].copy()

        full_report = full_report.merge(
            score_columns,
            on=["Symbol", "Timeframe"],
            how="left",
            suffixes=("", "_new"),
        )

        for col in ["BuyWatchScore", "SellWatchScore"]:
            new_col = col + "_new"

            if new_col in full_report.columns:
                if col in full_report.columns:
                    full_report[col] = full_report[col].fillna(
                        full_report[new_col]
                    )
                    full_report.drop(columns=[new_col], inplace=True)
                else:
                    full_report.rename(
                        columns={new_col: col},
                        inplace=True,
                    )

    # ------------------------------------------------------------
    # WRITE CSV FILES
    # ------------------------------------------------------------

    SIGNAL_DIR.mkdir(parents=True, exist_ok=True)

    full_report_file = SIGNAL_DIR / "daily_signal_report.csv"
    buy_file = SIGNAL_DIR / "daily_top20_buy.csv"
    sell_file = SIGNAL_DIR / "daily_top20_sell.csv"
    buy_watch_file = SIGNAL_DIR / "daily_top20_buy_watchlist.csv"
    sell_watch_file = SIGNAL_DIR / "daily_top20_sell_watchlist.csv"

    full_report.to_csv(full_report_file, index=False)
    select_output(top20_buy).to_csv(buy_file, index=False)
    select_output(top20_sell).to_csv(sell_file, index=False)
    select_output(
        top20_buy_watch, ["BuyWatchScore"]
    ).to_csv(buy_watch_file, index=False)
    select_output(
        top20_sell_watch, ["SellWatchScore"]
    ).to_csv(sell_watch_file, index=False)

    # ------------------------------------------------------------
    # DISPLAY RESULTS
    # ------------------------------------------------------------

    print()
    print("=" * 80)
    print("TOP 20 BUY SIGNALS")
    print("=" * 80)

    if top20_buy.empty:
        print("None today.")
    else:
        print(
            top20_buy[
                [
                    c for c in [
                        "Symbol",
                        "Category",
                        "Timeframe",
                        "Price",
                        "RSI",
                        "ADX",
                        "Score",
                    ]
                    if c in top20_buy.columns
                ]
            ].to_string(index=False)
        )

    print()
    print("=" * 80)
    print("TOP 20 BUY WATCHLIST")
    print("=" * 80)

    if top20_buy_watch.empty:
        print("None qualified today.")
    else:
        print(
            top20_buy_watch[
                [
                    c for c in [
                        "Symbol",
                        "Category",
                        "Timeframe",
                        "Price",
                        "RSI",
                        "ADX",
                        "BuyWatchScore",
                    ]
                    if c in top20_buy_watch.columns
                ]
            ].to_string(index=False)
        )

    print()
    print("=" * 80)
    print("TOP 20 SELL SIGNALS")
    print("=" * 80)

    if top20_sell.empty:
        print("None today.")
    else:
        print(
            top20_sell[
                [
                    c for c in [
                        "Symbol",
                        "Category",
                        "Timeframe",
                        "Price",
                        "RSI",
                        "ADX",
                        "Score",
                    ]
                    if c in top20_sell.columns
                ]
            ].to_string(index=False)
        )

    print()
    print("=" * 80)
    print("TOP 20 SELL WATCHLIST")
    print("=" * 80)

    if top20_sell_watch.empty:
        print("None qualified today.")
    else:
        print(
            top20_sell_watch[
                [
                    c for c in [
                        "Symbol",
                        "Category",
                        "Timeframe",
                        "Price",
                        "RSI",
                        "ADX",
                        "SellWatchScore",
                    ]
                    if c in top20_sell_watch.columns
                ]
            ].to_string(index=False)
        )

    print()
    print("=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"Total scanner rows       : {len(signals)}")
    print(f"BUY signals              : {len(buys)}")
    print(f"SELL signals             : {len(sells)}")
    print(f"BUY watchlist qualified  : {len(buy_watch)}")
    print(f"SELL watchlist qualified : {len(sell_watch)}")
    print(f"Watchlist minimum score  : {WATCHLIST_MIN_SCORE}")

    print()
    print("Created:")
    print(f"  {full_report_file}")
    print(f"  {buy_file}")
    print(f"  {sell_file}")
    print(f"  {buy_watch_file}")
    print(f"  {sell_watch_file}")


if __name__ == "__main__":
    main()
